languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "BEAMjourney"

[params]
  dateFormat = "2006 January 02"
  mainSections = ["posts"]
  description = "Posts about engineering, programming, software development including Elixir, Phoneix, Erlang, BEAM and personal interests"

[params.author]
  name = "David J Sweeney"
  # image = "images/david-portrait.jpg"
  headline = "Engineer, Programmer, Problem solver"
  # bio = "A little bit about you"
  links = [
    { email = "mailto:sweeneydavidj@gmail.com" },
    { link = "https://sweeneydavidj.com/" },
    { github = "https://github.com/sweeneydavidj" },
    { linkedin = "https://linkedin.com/in/sweeneydavidj" },
    # { mastodon = "https://mastodon.instance/@username" },
  ]
